Fix installation on R 2.15.2
Got the following error with gcc / g++ 4.8.4 (Ubuntu 14.04.5 LTS):
stri_stringi.cpp:308:34: error: invalid conversion from ‘int’ to ‘Rboolean’ [-fpermissive]
    R_useDynamicSymbols(dll, FALSE);

The error is probably due to TRUE and FALSE being defined in
Rdefines.h, and also as part of an enum in R_ext/Boolean.h.

The latter file currently has a remark:

/* These conflict with definitions in R_ext/Boolean.h,
   but spatstat relies on them in a C file */